name: mirrorc_test

on:
  workflow_dispatch:

jobs:
  mirrorchyan_uploading:
    runs-on: windows-2025
    steps:

      - uses: actions/download-artifact@v4
        with:
          path: downloads
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: 15793622213

      - name: 📥 Download kachina-builder dev
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: "YuehaiTeam/kachina-installer"
          workflow: "build.yml"
          name: artifact
          branch: main
          event: push
          workflow_conclusion: success

      - name: Embed Dotnet and VCRedist
        shell: bash
        run: |
          # dotnet
          VERSION_URL="https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/8.0/latest.version"
          VERSION=$(curl -fsSL "$VERSION_URL" | tr -d '\r\n')
          if [ -z "$VERSION" ]; then
              echo "Cannot get the latest version from $VERSION_URL"
              exit 1
          fi
          INSTALLER_URL="https://builds.dotnet.microsoft.com/dotnet/WindowsDesktop/${VERSION}/windowsdesktop-runtime-${VERSION}-win-x64.exe"
          OUTPUT="windowsdesktop-runtime-${VERSION}-win-x64.exe"
          echo "Downloading Windows Desktop Runtime version $VERSION from $INSTALLER_URL"
          curl -fSL -o "$OUTPUT" "$INSTALLER_URL"
          # vcredist
          echo "Downloading VCRedist"
          curl -fSL -o "vc_redist.x64.exe" "https://aka.ms/vs/17/release/vc_redist.x64.exe"
          # embed
          echo "Embedding runtimes"
          ./kachina-builder.exe append -o ./downloads/BetterGI_Install/BetterGI.Install.*.exe -f "$OUTPUT" -n "Microsoft.DotNet.DesktopRuntime.8" -f "vc_redist.x64.exe" -n "Microsoft.VCRedist.2015+.x64"

      - name: Extract 7z and create zip
        shell: bash
        run: |
          cd downloads/BetterGI_7z
          7z x BetterGI_v*.7z -oun7z
          mv ../BetterGI_Metadata/metadata.json ./un7z/BetterGI/.metadata.json
          7z a -tzip BetterGI.zip un7z/BetterGI -mx=5 -mf=BCJ2 -r -y
          ls .
          ls ./un7z/BetterGI
          choco install wget --no-progress 
          
      - name: Upload Zip
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: local
          mirrorchyan_rid: BGI
          filename: "downloads/BetterGI_7z/BetterGI.zip"
          version_name: ${{ needs.validate.outputs.version }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: win
          arch: x64
      
      - name: Upload Install.exe
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: local
          mirrorchyan_rid: BGI
          filename: "downloads/BetterGI_Install/BetterGI.Install.*.exe"
          version_name: ${{ needs.validate.outputs.version }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

